In [12]:
import numpy as np
from numpy import random
from numpy.lib.stride_tricks import sliding_window_view

Nparray=np.round(20*np.random.rand(100))

def Rollingwindow():
    window=3
    windows=sliding_window_view(Nparray,window)

    for x in windows:
        W_mean=x.mean()
        print(x)
        print(W_mean)
        print(" ")
        print(" ")


Rollingwindow()


[19.  8. 15.]
14.0
 
 
[ 8. 15. 18.]
13.666666666666666
 
 
[15. 18.  6.]
13.0
 
 
[18.  6.  3.]
9.0
 
 
[ 6.  3. 15.]
8.0
 
 
[ 3. 15.  7.]
8.333333333333334
 
 
[15.  7. 17.]
13.0
 
 
[ 7. 17. 15.]
13.0
 
 
[17. 15.  2.]
11.333333333333334
 
 
[15.  2.  9.]
8.666666666666666
 
 
[2. 9. 4.]
5.0
 
 
[ 9.  4. 14.]
9.0
 
 
[ 4. 14. 10.]
9.333333333333334
 
 
[14. 10.  2.]
8.666666666666666
 
 
[10.  2. 18.]
10.0
 
 
[ 2. 18. 13.]
11.0
 
 
[18. 13.  2.]
11.0
 
 
[13.  2. 12.]
9.0
 
 
[ 2. 12. 16.]
10.0
 
 
[12. 16. 14.]
14.0
 
 
[16. 14. 14.]
14.666666666666666
 
 
[14. 14. 16.]
14.666666666666666
 
 
[14. 16.  4.]
11.333333333333334
 
 
[16.  4. 13.]
11.0
 
 
[ 4. 13.  2.]
6.333333333333333
 
 
[13.  2.  8.]
7.666666666666667
 
 
[ 2.  8. 10.]
6.666666666666667
 
 
[ 8. 10.  8.]
8.666666666666666
 
 
[10.  8.  8.]
8.666666666666666
 
 
[ 8.  8. 12.]
9.333333333333334
 
 
[ 8. 12. 17.]
12.333333333333334
 
 
[12. 17. 16.]
15.0
 
 
[17. 16.  5.]
12.666666666666666
 
 
[16.  5.  1.]
7.33333

In [20]:
def normalizeData():

    std=np.std(Nparray)
    mean=np.mean(Nparray)

    print("Z_score")
    z_score=Nparray-mean/std
    print("length",len(z_score))
    print()
    print(z_score)


    print()
    print("Outliers")
    Outliers=z_score[np.abs(z_score)>2]
    print("length",len(Outliers))
    print()
    print(Outliers)





normalizeData()




Z_score
length 100

[17.18468207  6.18468207 13.18468207 16.18468207  4.18468207  1.18468207
 13.18468207  5.18468207 15.18468207 13.18468207  0.18468207  7.18468207
  2.18468207 12.18468207  8.18468207  0.18468207 16.18468207 11.18468207
  0.18468207 10.18468207 14.18468207 12.18468207 12.18468207 14.18468207
  2.18468207 11.18468207  0.18468207  6.18468207  8.18468207  6.18468207
  6.18468207 10.18468207 15.18468207 14.18468207  3.18468207 -0.81531793
 15.18468207  6.18468207 16.18468207 14.18468207  5.18468207 11.18468207
  1.18468207 15.18468207 -0.81531793 11.18468207  3.18468207 12.18468207
 16.18468207 14.18468207 12.18468207  3.18468207 16.18468207 14.18468207
 16.18468207  6.18468207 18.18468207  3.18468207 13.18468207  8.18468207
  1.18468207 14.18468207  8.18468207 15.18468207  8.18468207 15.18468207
  0.18468207 14.18468207 -1.81531793 11.18468207 16.18468207  6.18468207
  3.18468207 -1.81531793 12.18468207 11.18468207  1.18468207 10.18468207
  0.18468207 17.18468207 11.184